routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\admin\roleController;
use App\Http\Controllers\user\petitionController;
use App\Http\Controllers\admin\categoryController;
use App\Http\Controllers\admin\subcategoryController;
use App\Http\Controllers\admin\MembersController;
use App\Http\Controllers\admin\AmessengerController;
use App\Http\Controllers\Architecture\ProductController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main.layouts.master');
})->name('main.page');

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'dashboard','middleware'=>['auth' ,'admin']],function () {
   Route::get('/',[\App\Http\Controllers\HomeController::class,'adminpanel'])->name('adminpanel');
   Route::get('/setting',[\App\Http\Controllers\HomeController::class,'setting'])->name('setting');
   Route::put('/update/setting/{user}',[\App\Http\Controllers\HomeController::class,'update_setting'])->name('update.setting');
   Route::resource('/role',roleController::class);
   Route::get('/dashboard_notifications',[petitionController::class,'notifications'])->name('dashboard_notifications');
   Route::get('/notification/show/{petition}',[petitionController::class,'notificationShow'])->name('notification.show');
   Route::get('/notification/accept/{petition}',[petitionController::class,'notification_accept'])->name('dashboard.notification.accept');
   Route::post('/notification/cancel/{petition}',[petitionController::class,'notification_cancel'])->name('dashboard.notification.cancel');
   Route::resource('/category',categoryController::class);
   Route::resource('/subcategory',subcategoryController::class);
   Route::get('/architecture',[MembersController::class,'architecture'])->name('dashboard.architecture');
   Route::get('/users',[MembersController::class,'users'])->name('dashboard.users');
   Route::get('/receive',[ProductController::class,'receive'])->name('receive.product');
   Route::get('/receive/{product}',[ProductController::class,'product_show_receive'])->name('product.show_receive');
   Route::get('/product/press_accept/{product}',[ProductController::class,'press_accept'])->name('product.press_accept');
   Route::post('/product/cancel/{product}',[ProductController::class,'reason'])->name('product.reason');
   Route::get('/accept',[ProductController::class,'accept_product'])->name('accept.product');
   Route::get('/cancel',[ProductController::class,'cancel_product'])->name('cancel.product');
   Route::post('/product/block',[ProductController::class,'block_product'])->name('product.block');
   Route::post('/spam/architecture/{architect}',[App\Http\Controllers\Architecture\spamController::class,'architecture_spam'])->name('architecture.spam');
   Route::get('/nospam/architecture/{architect}',[App\Http\Controllers\Architecture\spamController::class,'nospam'])->name('architecture.nospam');
   Route::post('/spam/user/{user}',[App\Http\Controllers\Architecture\spamController::class,'user_spam'])->name('user.spam');
   Route::get('/nospam/user/{user}',[App\Http\Controllers\Architecture\spamController::class,'user_nospam'])->name('user.nospam');
   Route::get('/messenger',[AmessengerController::class,'create'])->name('messengers.messenger');
   Route::get('/chat/{messenger}',[AmessengerController::class,'chat_member'])->name('messengers.chat');
   Route::post('/admin/text/{account}',[AmessengerController::class,'admin_text_messenger'])->name('admin_text_messenger');
   Route::post('/search/',[AmessengerController::class,'search'])->name('messengers.search');
   Route::get('/contact',[App\Http\Controllers\Main\ContactController::class, 'receive_contact'])->name('receive.contact');
});
Route::group(['prefix' => 'arch','middleware'=>['auth' ,'architec']],function () {
    Route::get('/',[\App\Http\Controllers\HomeController::class,'architecpanel'])->name('architecpanel');
    Route::get('/architek/setting',[\App\Http\Controllers\HomeController::class,'archsetting'])->name('architek_setting');
    Route::put('/setting/{user}',[\App\Http\Controllers\HomeController::class,'archupdate'])->name('update');
    Route::resource('/product',ProductController::class);
//    Route::get('/product/receive',[ProductController::class,'productReceive'])->name('product.receive');
    Route::post('/select/category',[ProductController::class,'select_category'])->name('architec.category');
    Route::post('/select/subcategory',[ProductController::class,'select_subcategory'])->name('architec.subcategory');
    Route::get('/chat',[App\Http\Controllers\Admin\AmessengerController::class,'chat_with_admin'])->name('admin_chat');
    Route::post('/message/text',[App\Http\Controllers\Admin\AmessengerController::class,'architec_text_message'])->name('architec_text_message');
});


Route::group(['prefix'=>'use','middleware'=>['auth' , 'user']],function () {
    Route::get('/',[\App\Http\Controllers\HomeController::class,'userpanel'])->name('userpanel');
    Route::get('/setting',[\App\Http\Controllers\HomeController::class,'usersetting'])->name('user.setting');
    Route::put('/update/setting/{user}',[\App\Http\Controllers\HomeController::class,'userupdate'])->name('user.update');
    Route::resource('/petition',petitionController::class);
    Route::get('/chat',[App\Http\Controllers\Admin\AmessengerController::class,'chat_with_user'])->name('user_chat');
    Route::post('messenger/text',[App\Http\Controllers\Admin\AmessengerController::class,'user_text_messenger'])->name('user_text_messenger');
});
Route::get('/main/contact',[App\Http\Controllers\Main\ContactController::class,'contact'])->name('main_contact');
Route::post('/send',[App\Http\Controllers\Main\ContactController::class,'store'])->name('contact.store');

app/Models/Subcategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Subcategory extends Model
{
    use HasFactory;
}

app/Http/Controllers/admin/subcategoryController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Subcategory;
use Illuminate\Http\Request;

class subcategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subcategories = Subcategory::select('subcategories.id','subcategories.subcategory_name','subcategories.created_at','subcategories.category_id','categories.category_name')
        ->join('categories','categories.id' , '=' , 'subcategories.category_id')->get();
        return view('admin.subcategories.view',compact('subcategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.subcategories.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'category_id' => 'required',
            'subcategory_name'=>'required'
        ]);
        $category_id = $request->input('category_id');
       $subcategories = new Subcategory();
       for ($i=0 ; $i<count($request->subcategory_name);$i++)
       {
           $subcategories = new Subcategory();
           $subcategories->category_id =$category_id;
           $subcategories->subcategory_name = $request->subcategory_name[$i];
           $subcategories->save();
       }

       return redirect()->back();
     }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Subcategory $subcategory)
    {
        $categories = Category::all();
        return view('admin.subcategories.edit',compact('subcategory','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subcategory $subcategory)
    {
        $request->validate([
            'subcategory_name' => 'required'
        ]);
        $category_id = $request->input('category_id');
        $subcategory_name = $request->input('subcategory_name');
        $subcategory->category_id = $category_id;
        $subcategory->subcategory_name = $subcategory_name;
        $subcategory->update();
        return redirect()->route('subcategory.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subcategory $subcategory)
    {
        $subcategory->delete();
        return redirect()->route('subcategory.index');
    }
}

resources/views/admin/subcategories/create.blade.php
@extends('admin.layouts.master')
@section('title' , 'Add subcategory')
@section('content')
    <div class="select2-drpdwn">
        <div class="row">
            <div class="col-md-12">
                <div class="card mt-3 ">
                    <div class="card-header">
                        <h5 class="card-title">Add category</h5>
                    </div>
                    <form action="{{route('subcategory.store')}}" method="post" >
                        @csrf
                        <div class="card-body o-hidden" >
                            <div class="mb-2">
                                <div class="col-form-label">Category title</div>
                                <select name="category_id" class="js-example-placeholder-multiple col-sm-12  @error('category_id') is-invalid @enderror" >
                                    <option selected disabled >Select category</option>
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}">{{$category->category_name}}</option>
                                    @endforeach
                                </select>
                                @error('category_id')
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                                @enderror
                            </div>

                                <div class="col-form-label">Subcategory title</div>
                                <div class="d-flex mb-3">
                                    <input autocomplete="off" placeholder="subcategory name" style="margin-right: 20px;"
                                     name="subcategory_name[]" type="text" class="form-control w-85
                                     @error('subcategory_name') is-invalid @enderror ">
                                    @error('subcategory_name')
                                        <span class="invalid-feedback" role="alert">
                                             <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                     <button class="btn" style="background: #0f6e3a;color: white;font-weight:
                                      bold;float: right;margin-left: 20px" id="add_btn">+</button>
                                </div>
                                    <div id="child">

                                    </div>
                                <div class="text-start mt-4">
                                    <input type="submit" value="Add subcategory" class="btn btn-primary">
                                </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

@endsection
{{--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>--}}
@push('script')
    <script>
        $(document).ready(function ()
        {
            $('#add_btn').click(function (e)
            {
                e.preventDefault();
                $('#child').append(`
                          <div class="d-flex mb-3">
                             <input autocomplete="off" style="margin-right: 20px;" name="subcategory_name[]" type="text" class="form-control w-85" placeholder="subcategory name">
                            <button id="remove_btn" class="btn btn-danger"  style="background: #0f6e3a;color: white;font-weight: bold;float: right;margin-left: 20px" >x</button>
                          </div>
                       `);

            });

        });
        $(document).on('click','#remove_btn',function (e)
        {
            e.preventDefault();
            let row_item = $(this).parent();
            $(row_item).remove();
        });
    </script>
@endpush

resources/views/admin/subcategories/edit.blade.php
@extends('admin.layouts.master')
@section('title' , 'Edit subcategory')
@section('content')
    <div class="select2-drpdwn">
        <div class="row">
            <div class="col-md-12">
                <div class="card mt-3 ">
                    <div class="card-header">
                        <h5 class="card-title">Update category</h5>
                    </div>
                    <form action="{{route('subcategory.update',$subcategory)}}" method="post" >
                        @csrf
                        @method('PUT')
                        <div class="card-body o-hidden" >
                            <div class="mb-2">
                                <div class="col-form-label">Category title</div>
                                <select name="category_id" class="js-example-placeholder-multiple col-sm-12  @error('category_id') is-invalid @enderror" >
                                    <option selected disabled >Select category</option>
                                    @foreach($categories as $category)
                                        @if($category->id == $subcategory->category_id)
                                            {
                                              <option selected value="{{$category->id}}">{{$category->category_name}}</option>
                                            }
                                        @else()
                                            {
                                                <option value="{{$category->id}}">{{$category->category_name}}</option>
                                             }
                                        @endif
                                    @endforeach
                                </select>
                                @error('category_id')
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                                @enderror
                            </div>

                            <div class="col-form-label">Subcategory title</div>
                            <div class="d-flex mb-3">
                                <input value="{{$subcategory->subcategory_name}}" style="margin-right: 20px;" name="subcategory_name" type="text" class="form-control w-100  @error('subcategory_name') is-invalid @enderror ">
                                @error('subcategory_name')
                                <span class="invalid-feedback" role="alert">
                                             <strong>{{ $message }}</strong>
                                        </span>
                                @enderror
                            </div>
                            <div class="text-start mt-4">
                                <input type="submit" value="update subcategory" class="btn btn-primary">
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

@endsection
{{--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>--}}
{{--@push('script')--}}
{{--    <script>--}}
{{--        $(document).ready(function ()--}}
{{--        {--}}
{{--            $('#add_btn').click(function (e)--}}
{{--            {--}}
{{--                e.preventDefault();--}}
{{--                $('#child').append(`--}}
{{--                          <div class="d-flex mb-3">--}}
{{--                             <input style="margin-right: 20px;" name="subcategory_name[]" type="text" class="form-control w-85" placeholder="subcategory name">--}}
{{--                            <button id="remove_btn" class="btn btn-danger"  style="background: #0f6e3a;color: white;font-weight: bold;float: right;margin-left: 20px" >x</button>--}}
{{--                          </div>--}}
{{--                       `);--}}

{{--            });--}}

{{--        });--}}
{{--        $(document).on('click','#remove_btn',function (e)--}}
{{--        {--}}
{{--            e.preventDefault();--}}
{{--            let row_item = $(this).parent();--}}
{{--            $(row_item).remove();--}}
{{--        });--}}
{{--    </script>--}}
{{--@endpush--}}

resources/views/admin/subcategories/view.blade.php
@extends('admin.layouts.master')
@section('title' , 'view subcategories')
@section('content')
    <br>
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header d-flex align-items-center justify-content-between">
                        <h5 class="mb-3">All subcategories</h5>
                        <a class="btn btn-success" href="{{route('subcategory.create')}}">Create subcategory</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <div id="advance-1_wrapper" class="dataTables_wrapper"><div class="dataTables_length" id="advance-1_length"><label>Show <select name="advance-1_length" aria-controls="advance-1" class=""><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div><div id="advance-1_filter" class="dataTables_filter"><label>Search:<input type="search" class="" placeholder="" aria-controls="advance-1"></label></div><table class="display dataTable" id="advance-1" role="grid" aria-describedby="advance-1_info">
                                    <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="advance-1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 171.3px;">
                                            №
                                        </th>
                                        <th class="sorting_asc" tabindex="0" aria-controls="advance-1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 171.3px;">
                                            Category title
                                        </th>
                                        <th class="sorting_asc" tabindex="0" aria-controls="advance-1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 171.3px;">
                                            Subcategory title
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="advance-1" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 280.5px;">
                                            Created date
                                        </th>

                                        <th class="sorting" tabindex="0" aria-controls="advance-1" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending" style="width: 116.312px;">
                                            action
                                        </th>

                                    </tr>
                                    </thead>

                                    <tbody>
                                        @foreach($subcategories as $key=>$subcategory)
                                            <tr>
                                                <td>{{$key+1}}</td>
                                                <td>{{$subcategory->category_name}}</td>
                                                <td>{{$subcategory->subcategory_name}}</td>
                                                <td>{{$subcategory->created_at}}</td>
                                                <td class="d-flex">
                                                    <a class="btn btn-primary" href="{{route('subcategory.edit',$subcategory)}}">Edit</a>&nbsp;
                                                    <form action="{{route('subcategory.destroy',$subcategory)}}" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

@endsection